spring.docker.compose.enabled=false

# allowPublicKeyRetrieval: Permite obtener una clave publica del servidor para cifrar la contraseña
#
#createDatabaseIfNotExist=true: Permite crear la base de datos antes de que hibernate intente crear las tablas
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_diagnostico?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Al levantar el docker update crea las tablas nuevas y actualiza las anteriores, lo que permite mantener la informacion
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Esto asegura que el script corra después de crear las tablas
spring.jpa.defer-datasource-initialization=true
# Ejecutar siempre el archivo data.sql al iniciar
spring.sql.init.mode=always
# Esta línea es CLAVE cuando usas Hibernate + data.sql
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
